"""Commit readiness flow for SelfDev.

This phase does not run git commit.
It evaluates whether a task has the required artifacts for local commit readiness.
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from selfdev.runtime.artifact_registry import ArtifactRecord, ArtifactRegistry
from selfdev.runtime.kanban import KanbanBoard
from selfdev.runtime.state_manager import StateManager
from selfdev.tools.artifact_gate import validate_artifact_record
from selfdev.tools.commit_gate import evaluate_commit_readiness


DEFAULT_REQUIRED_ARTIFACTS = [
    "senior_review",
    "safety_report",
    "verification_report",
    "runner_report",
]


@dataclass
class CommitReadinessFlowResult:
    task_id: str
    status: str
    commit_status: str
    report_path: str | None = None
    artifact_id: str | None = None
    missing: list[str] = field(default_factory=list)
    reasons: list[str] = field(default_factory=list)
    state_path: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "task_id": self.task_id,
            "status": self.status,
            "commit_status": self.commit_status,
            "report_path": self.report_path,
            "artifact_id": self.artifact_id,
            "missing": self.missing,
            "reasons": self.reasons,
            "state_path": self.state_path,
        }


def _now_run_id() -> str:
    return time.strftime("run-%Y%m%d-%H%M%S")


def _write_commit_request_report(
    workspace: Path,
    task_id: str,
    commit_status: str,
    missing: list[str],
    reasons: list[str],
) -> Path:
    approvals_dir = workspace / "approvals"
    approvals_dir.mkdir(parents=True, exist_ok=True)
    report_path = approvals_dir / f"{task_id}.commit_request.md"

    missing_text = "\n".join([f"- {item}" for item in missing]) if missing else "- None"
    reason_text = "\n".join([f"- {item}" for item in reasons]) if reasons else "- No blocking reason."

    content = f"""# Commit Readiness Report

## Task ID

{task_id}

## Commit Status

{commit_status}

## Missing Requirements

{missing_text}

## Reasons

{reason_text}

## Notes

This report was generated by the deterministic Commit Readiness Flow.

No git commit was executed.
No git push was executed.
No merge was executed.
No release was created.
"""
    report_path.write_text(content, encoding="utf-8")
    return report_path


def evaluate_task_commit_readiness(
    task_id: str,
    workspace: Path | str = "data/agent_workspace",
    required_artifacts: list[str] | None = None,
) -> CommitReadinessFlowResult:
    workspace_path = Path(workspace)
    required_artifacts = required_artifacts or DEFAULT_REQUIRED_ARTIFACTS

    board = KanbanBoard(workspace_path)
    state = StateManager(workspace_path)
    registry = ArtifactRegistry(workspace_path)
    run_id = _now_run_id()

    try:
        task = board.get_task(task_id)
    except KeyError as exc:
        state_path = state.write_state(task_id, {
            "task_id": task_id,
            "run_id": run_id,
            "stage": "commit_readiness_failed",
            "status": "blocked",
            "reason": [str(exc)],
            "retry_count": 0,
        })
        return CommitReadinessFlowResult(
            task_id=task_id,
            status="blocked",
            commit_status="BLOCKED",
            missing=["task"],
            reasons=[str(exc)],
            state_path=str(state_path),
        )

    if task.get("status") != "commit_ready":
        reason = f"Task status is not ready for Commit Gate: {task.get('status')}"
        state_path = state.write_state(task_id, {
            "task_id": task_id,
            "run_id": run_id,
            "stage": "commit_readiness_blocked",
            "status": "blocked",
            "reason": [reason],
            "retry_count": 0,
        })
        return CommitReadinessFlowResult(
            task_id=task_id,
            status="blocked",
            commit_status="BLOCKED",
            missing=[],
            reasons=[reason],
            state_path=str(state_path),
        )

    artifacts = task.get("artifacts", {})
    requirements = {
        artifact_type: artifact_type in artifacts
        for artifact_type in required_artifacts
    }

    readiness = evaluate_commit_readiness(requirements)
    commit_status = readiness.status
    missing = readiness.missing
    reasons = [f"Missing required artifact: {item}" for item in missing]

    next_status = "commit_ready" if commit_status == "READY" else "blocked"

    report_path = _write_commit_request_report(
        workspace=workspace_path,
        task_id=task_id,
        commit_status=commit_status,
        missing=missing,
        reasons=reasons,
    )

    artifact_id = f"{task_id}.commit_gate.commit_request"
    record = ArtifactRecord(
        artifact_id=artifact_id,
        task_id=task_id,
        agent_id="commit_gate",
        artifact_type="commit_request",
        path=f"approvals/{task_id}.commit_request.md",
        status="collected",
    )

    gate_result = validate_artifact_record(record.to_dict(), workspace=workspace_path)
    if not gate_result.passed:
        state_path = state.write_state(task_id, {
            "task_id": task_id,
            "run_id": run_id,
            "stage": "commit_readiness_artifact_invalid",
            "status": "blocked",
            "reason": gate_result.reasons,
            "retry_count": 0,
        })
        return CommitReadinessFlowResult(
            task_id=task_id,
            status="blocked",
            commit_status="BLOCKED",
            report_path=str(report_path),
            artifact_id=artifact_id,
            missing=missing,
            reasons=gate_result.reasons,
            state_path=str(state_path),
        )

    try:
        registry.register(record)
    except ValueError as exc:
        if "already registered" not in str(exc):
            raise

    board.attach_artifact(task_id, "commit_request", artifact_id)
    board.update_status(task_id, next_status)

    state_path = state.write_state(task_id, {
        "task_id": task_id,
        "run_id": run_id,
        "stage": "commit_readiness_completed",
        "status": next_status,
        "current_agent": "commit_gate",
        "commit_status": commit_status,
        "missing": missing,
        "reason": reasons,
        "last_successful_checkpoint": "commit_readiness_completed" if commit_status == "READY" else None,
        "artifact_id": artifact_id,
        "retry_count": 0,
    })

    return CommitReadinessFlowResult(
        task_id=task_id,
        status=next_status,
        commit_status=commit_status,
        report_path=str(report_path),
        artifact_id=artifact_id,
        missing=missing,
        reasons=reasons,
        state_path=str(state_path),
    )
