"""Full deterministic dry run flow for SelfDev.

This flow simulates one safe task lifecycle without LLM calls,
without shell execution, without patch application, and without git commit.
"""

from __future__ import annotations

import json
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from selfdev.runtime.artifact_collector import collect_artifact_reply
from selfdev.runtime.commit_readiness_flow import evaluate_task_commit_readiness
from selfdev.runtime.dispatcher import dispatch_manifest_file
from selfdev.runtime.manifest_validator import load_manifest, validate_manifest_dict
from selfdev.runtime.runner_flow import write_runner_report
from selfdev.runtime.safety_flow import write_safety_decision
from selfdev.runtime.senior_review_gate import write_senior_review
from selfdev.runtime.verification_flow import write_verification_report


@dataclass
class FullDryRunResult:
    task_id: str
    status: str
    workspace: str
    stages: dict[str, Any] = field(default_factory=dict)
    reasons: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "task_id": self.task_id,
            "status": self.status,
            "workspace": self.workspace,
            "stages": self.stages,
            "reasons": self.reasons,
        }


def _now_run_id() -> str:
    return time.strftime("run-%Y%m%d-%H%M%S")


def _artifact_content(task_id: str, agent_id: str, artifact_type: str) -> str:
    title = artifact_type.replace("_", " ").title()
    return f"""# {title}

## Task ID

{task_id}

## Agent

{agent_id}

## Artifact Type

{artifact_type}

## Notes

This artifact was generated by the deterministic full dry run.

No LLM was called.
No shell command was executed.
No patch was applied.
"""


def _write_mock_artifact_reply(
    manifest: dict[str, Any],
    workspace: Path,
    agent_id: str,
) -> Path:
    task_id = manifest["task_id"]
    run_id = _now_run_id()

    artifact_paths: dict[str, str] = {}

    for artifact_type in manifest["required_outputs"]:
        artifact_rel_path = f"docs/{task_id}.{agent_id}_{artifact_type}.md"
        artifact_path = workspace / artifact_rel_path
        artifact_path.parent.mkdir(parents=True, exist_ok=True)
        artifact_path.write_text(
            _artifact_content(task_id, agent_id, artifact_type),
            encoding="utf-8",
        )
        artifact_paths[artifact_type] = artifact_rel_path

    outbox_dir = workspace / "agents" / agent_id / "outbox"
    outbox_dir.mkdir(parents=True, exist_ok=True)

    reply_path = outbox_dir / f"msg-{task_id}-artifact-ready.json"
    reply = {
        "message_id": f"msg-{task_id}-artifact-ready",
        "run_id": run_id,
        "from_agent": agent_id,
        "to_agent": "siwa",
        "task_id": task_id,
        "message_type": "artifact_ready",
        "status": "completed",
        "artifacts": artifact_paths,
    }

    reply_path.write_text(json.dumps(reply, indent=2, ensure_ascii=False), encoding="utf-8")
    return reply_path


def run_full_dry_run(
    manifest_path: Path | str,
    workspace: Path | str = "data/agent_workspace",
    runner_action: str = "git_apply_check",
) -> FullDryRunResult:
    workspace_path = Path(workspace)
    workspace_path.mkdir(parents=True, exist_ok=True)

    manifest = load_manifest(manifest_path)
    task_id = str(manifest.get("task_id", "unknown"))

    stages: dict[str, Any] = {}

    validation = validate_manifest_dict(manifest)
    stages["manifest_validation"] = {
        "valid": validation.valid,
        "errors": validation.errors,
        "warnings": validation.warnings,
    }

    if not validation.valid:
        return FullDryRunResult(
            task_id=task_id,
            status="manifest_invalid",
            workspace=str(workspace_path),
            stages=stages,
            reasons=validation.errors,
        )

    dispatch = dispatch_manifest_file(
        manifest_path=manifest_path,
        workspace=workspace_path,
    )
    stages["dispatch"] = dispatch.to_dict()

    if dispatch.status != "dispatched":
        return FullDryRunResult(
            task_id=task_id,
            status=dispatch.status,
            workspace=str(workspace_path),
            stages=stages,
            reasons=dispatch.reasons,
        )

    if not dispatch.target_agent:
        return FullDryRunResult(
            task_id=task_id,
            status="blocked",
            workspace=str(workspace_path),
            stages=stages,
            reasons=["Dispatch did not return target_agent."],
        )

    reply_path = _write_mock_artifact_reply(
        manifest=manifest,
        workspace=workspace_path,
        agent_id=dispatch.target_agent,
    )
    stages["mock_artifact_reply"] = {
        "reply_path": str(reply_path),
        "agent_id": dispatch.target_agent,
    }

    collection = collect_artifact_reply(
        reply_path=reply_path,
        workspace=workspace_path,
        required_artifact_types=list(manifest["required_outputs"]),
    )
    stages["artifact_collection"] = collection.to_dict()

    if collection.status != "ready_for_senior":
        return FullDryRunResult(
            task_id=task_id,
            status=collection.status,
            workspace=str(workspace_path),
            stages=stages,
            reasons=collection.reasons,
        )

    senior = write_senior_review(
        task_id=task_id,
        decision="approve_for_runner",
        reasons=["Full dry run artifacts are complete."],
        workspace=workspace_path,
    )
    stages["senior_review"] = senior.to_dict()

    if senior.status != "ready_for_verification":
        return FullDryRunResult(
            task_id=task_id,
            status=senior.status,
            workspace=str(workspace_path),
            stages=stages,
            reasons=senior.reasons,
        )

    artifact_changed_paths = [
        f"docs/{task_id}.{dispatch.target_agent}_{artifact_type}.md"
        for artifact_type in manifest["required_outputs"]
    ]

    safety = write_safety_decision(
        task_id=task_id,
        requested_actions=["write_artifact"],
        changed_paths=artifact_changed_paths,
        workspace=workspace_path,
    )
    stages["safety"] = safety.to_dict()

    if safety.safety_status != "PASS":
        return FullDryRunResult(
            task_id=task_id,
            status=safety.status,
            workspace=str(workspace_path),
            stages=stages,
            reasons=safety.reasons,
        )

    verification = write_verification_report(
        task_id=task_id,
        required_files=artifact_changed_paths,
        workspace=workspace_path,
    )
    stages["verification"] = verification.to_dict()

    if verification.verification_status != "PASS":
        return FullDryRunResult(
            task_id=task_id,
            status=verification.status,
            workspace=str(workspace_path),
            stages=stages,
            reasons=verification.reasons,
        )

    runner = write_runner_report(
        task_id=task_id,
        action=runner_action,
        workspace=workspace_path,
    )
    stages["runner"] = runner.to_dict()

    if runner.runner_status != "ACCEPTED":
        return FullDryRunResult(
            task_id=task_id,
            status=runner.status,
            workspace=str(workspace_path),
            stages=stages,
            reasons=runner.reasons,
        )

    commit = evaluate_task_commit_readiness(
        task_id=task_id,
        workspace=workspace_path,
    )
    stages["commit_readiness"] = commit.to_dict()

    if commit.commit_status != "READY":
        return FullDryRunResult(
            task_id=task_id,
            status=commit.status,
            workspace=str(workspace_path),
            stages=stages,
            reasons=commit.reasons,
        )

    return FullDryRunResult(
        task_id=task_id,
        status="dry_run_complete",
        workspace=str(workspace_path),
        stages=stages,
        reasons=[],
    )
