"""Runner request flow for SelfDev.

This phase does not execute commands.
It validates a requested Runner action and writes a Runner report artifact.
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from selfdev.runtime.artifact_registry import ArtifactRecord, ArtifactRegistry
from selfdev.runtime.kanban import KanbanBoard
from selfdev.runtime.state_manager import StateManager
from selfdev.tools.artifact_gate import validate_artifact_record
from selfdev.tools.runner import validate_runner_request


@dataclass
class RunnerFlowResult:
    task_id: str
    status: str
    runner_status: str
    action: str
    report_path: str | None = None
    artifact_id: str | None = None
    reasons: list[str] = field(default_factory=list)
    state_path: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "task_id": self.task_id,
            "status": self.status,
            "runner_status": self.runner_status,
            "action": self.action,
            "report_path": self.report_path,
            "artifact_id": self.artifact_id,
            "reasons": self.reasons,
            "state_path": self.state_path,
        }


def _now_run_id() -> str:
    return time.strftime("run-%Y%m%d-%H%M%S")


def _write_runner_report(
    workspace: Path,
    task_id: str,
    action: str,
    runner_status: str,
    reasons: list[str],
) -> Path:
    runner_dir = workspace / "runner"
    runner_dir.mkdir(parents=True, exist_ok=True)
    report_path = runner_dir / f"{task_id}.runner_report.md"

    reason_text = "\n".join([f"- {reason}" for reason in reasons]) if reasons else "- No blocking reason."

    content = f"""# Runner Report

## Task ID

{task_id}

## Requested Action

{action}

## Runner Status

{runner_status}

## Reasons

{reason_text}

## Notes

This report was generated by the deterministic Runner Request Flow.
No command was executed in this phase.
"""
    report_path.write_text(content, encoding="utf-8")
    return report_path


def write_runner_report(
    task_id: str,
    action: str,
    workspace: Path | str = "data/agent_workspace",
) -> RunnerFlowResult:
    workspace_path = Path(workspace)

    board = KanbanBoard(workspace_path)
    state = StateManager(workspace_path)
    registry = ArtifactRegistry(workspace_path)
    run_id = _now_run_id()

    try:
        task = board.get_task(task_id)
    except KeyError as exc:
        state_path = state.write_state(task_id, {
            "task_id": task_id,
            "run_id": run_id,
            "stage": "runner_failed",
            "status": "blocked",
            "reason": [str(exc)],
            "retry_count": 0,
        })
        return RunnerFlowResult(
            task_id=task_id,
            status="blocked",
            runner_status="BLOCKED",
            action=action,
            reasons=[str(exc)],
            state_path=str(state_path),
        )

    if task.get("status") != "verified":
        reason = f"Task status is not ready for Runner: {task.get('status')}"
        state_path = state.write_state(task_id, {
            "task_id": task_id,
            "run_id": run_id,
            "stage": "runner_blocked",
            "status": "blocked",
            "reason": [reason],
            "retry_count": 0,
        })
        return RunnerFlowResult(
            task_id=task_id,
            status="blocked",
            runner_status="BLOCKED",
            action=action,
            reasons=[reason],
            state_path=str(state_path),
        )

    runner_result = validate_runner_request(action)
    runner_status = runner_result.status
    reasons = runner_result.notes

    next_status = "commit_ready" if runner_status == "ACCEPTED" else "blocked"

    report_path = _write_runner_report(
        workspace=workspace_path,
        task_id=task_id,
        action=action,
        runner_status=runner_status,
        reasons=reasons,
    )

    artifact_id = f"{task_id}.runner.runner_report"
    record = ArtifactRecord(
        artifact_id=artifact_id,
        task_id=task_id,
        agent_id="runner",
        artifact_type="runner_report",
        path=f"runner/{task_id}.runner_report.md",
        status="collected",
    )

    gate_result = validate_artifact_record(record.to_dict(), workspace=workspace_path)
    if not gate_result.passed:
        state_path = state.write_state(task_id, {
            "task_id": task_id,
            "run_id": run_id,
            "stage": "runner_artifact_invalid",
            "status": "blocked",
            "reason": gate_result.reasons,
            "retry_count": 0,
        })
        return RunnerFlowResult(
            task_id=task_id,
            status="blocked",
            runner_status="BLOCKED",
            action=action,
            report_path=str(report_path),
            artifact_id=artifact_id,
            reasons=gate_result.reasons,
            state_path=str(state_path),
        )

    try:
        registry.register(record)
    except ValueError as exc:
        if "already registered" not in str(exc):
            raise

    board.attach_artifact(task_id, "runner_report", artifact_id)
    board.update_status(task_id, next_status)

    state_path = state.write_state(task_id, {
        "task_id": task_id,
        "run_id": run_id,
        "stage": "runner_completed",
        "status": next_status,
        "current_agent": "runner",
        "runner_status": runner_status,
        "action": action,
        "reason": reasons,
        "last_successful_checkpoint": "runner_completed" if runner_status == "ACCEPTED" else None,
        "artifact_id": artifact_id,
        "retry_count": 0,
    })

    return RunnerFlowResult(
        task_id=task_id,
        status=next_status,
        runner_status=runner_status,
        action=action,
        report_path=str(report_path),
        artifact_id=artifact_id,
        reasons=reasons,
        state_path=str(state_path),
    )
