"""Safety decision flow for SelfDev."""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from selfdev.runtime.artifact_registry import ArtifactRecord, ArtifactRegistry
from selfdev.runtime.kanban import KanbanBoard
from selfdev.runtime.state_manager import StateManager
from selfdev.tools.artifact_gate import validate_artifact_record
from selfdev.tools.safety_gate import check_actions, check_paths


@dataclass
class SafetyDecisionResult:
    task_id: str
    status: str
    safety_status: str
    report_path: str | None = None
    artifact_id: str | None = None
    reasons: list[str] = field(default_factory=list)
    state_path: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "task_id": self.task_id,
            "status": self.status,
            "safety_status": self.safety_status,
            "report_path": self.report_path,
            "artifact_id": self.artifact_id,
            "reasons": self.reasons,
            "state_path": self.state_path,
        }


def _now_run_id() -> str:
    return time.strftime("run-%Y%m%d-%H%M%S")


def _write_safety_report(
    workspace: Path,
    task_id: str,
    safety_status: str,
    requested_actions: list[str],
    changed_paths: list[str],
    reasons: list[str],
) -> Path:
    safety_dir = workspace / "safety"
    safety_dir.mkdir(parents=True, exist_ok=True)
    report_path = safety_dir / f"{task_id}.safety_report.md"

    action_text = "\n".join([f"- {item}" for item in requested_actions]) if requested_actions else "- None"
    path_text = "\n".join([f"- {item}" for item in changed_paths]) if changed_paths else "- None"
    reason_text = "\n".join([f"- {item}" for item in reasons]) if reasons else "- No blocking reason."

    content = f"""# Safety Report

## Task ID

{task_id}

## Safety Status

{safety_status}

## Requested Actions

{action_text}

## Changed Paths

{path_text}

## Reasons

{reason_text}

## Notes

This report was generated by the deterministic Safety Gate integration flow.
"""
    report_path.write_text(content, encoding="utf-8")
    return report_path


def write_safety_decision(
    task_id: str,
    requested_actions: list[str] | None = None,
    changed_paths: list[str] | None = None,
    workspace: Path | str = "data/agent_workspace",
) -> SafetyDecisionResult:
    workspace_path = Path(workspace)
    requested_actions = requested_actions or []
    changed_paths = changed_paths or []

    board = KanbanBoard(workspace_path)
    state = StateManager(workspace_path)
    registry = ArtifactRegistry(workspace_path)
    run_id = _now_run_id()

    try:
        task = board.get_task(task_id)
    except KeyError as exc:
        state_path = state.write_state(task_id, {
            "task_id": task_id,
            "run_id": run_id,
            "stage": "safety_failed",
            "status": "blocked",
            "reason": [str(exc)],
            "retry_count": 0,
        })
        return SafetyDecisionResult(
            task_id=task_id,
            status="blocked",
            safety_status="BLOCK",
            reasons=[str(exc)],
            state_path=str(state_path),
        )

    if task.get("status") not in {"ready_for_verification", "needs_review"}:
        reason = f"Task status is not ready for Safety Gate: {task.get('status')}"
        state_path = state.write_state(task_id, {
            "task_id": task_id,
            "run_id": run_id,
            "stage": "safety_blocked",
            "status": "blocked",
            "reason": [reason],
            "retry_count": 0,
        })
        return SafetyDecisionResult(
            task_id=task_id,
            status="blocked",
            safety_status="BLOCK",
            reasons=[reason],
            state_path=str(state_path),
        )

    action_result = check_actions(requested_actions)
    path_result = check_paths(changed_paths)

    reasons: list[str] = []
    reasons.extend(action_result.reasons)
    reasons.extend(path_result.reasons)

    safety_status = "PASS" if not reasons else "BLOCK"
    next_status = "ready_for_verification" if safety_status == "PASS" else "blocked"

    report_path = _write_safety_report(
        workspace=workspace_path,
        task_id=task_id,
        safety_status=safety_status,
        requested_actions=requested_actions,
        changed_paths=changed_paths,
        reasons=reasons,
    )

    artifact_id = f"{task_id}.safety_gate.safety_report"
    record = ArtifactRecord(
        artifact_id=artifact_id,
        task_id=task_id,
        agent_id="safety_gate",
        artifact_type="safety_report",
        path=f"safety/{task_id}.safety_report.md",
        status="collected",
    )

    gate_result = validate_artifact_record(record.to_dict(), workspace=workspace_path)
    if not gate_result.passed:
        state_path = state.write_state(task_id, {
            "task_id": task_id,
            "run_id": run_id,
            "stage": "safety_artifact_invalid",
            "status": "blocked",
            "reason": gate_result.reasons,
            "retry_count": 0,
        })
        return SafetyDecisionResult(
            task_id=task_id,
            status="blocked",
            safety_status="BLOCK",
            report_path=str(report_path),
            artifact_id=artifact_id,
            reasons=gate_result.reasons,
            state_path=str(state_path),
        )

    try:
        registry.register(record)
    except ValueError as exc:
        if "already registered" not in str(exc):
            raise

    board.attach_artifact(task_id, "safety_report", artifact_id)
    board.update_status(task_id, next_status)

    state_path = state.write_state(task_id, {
        "task_id": task_id,
        "run_id": run_id,
        "stage": "safety_completed",
        "status": next_status,
        "current_agent": "safety_gate",
        "safety_status": safety_status,
        "reason": reasons,
        "last_successful_checkpoint": "safety_completed" if safety_status == "PASS" else None,
        "artifact_id": artifact_id,
        "retry_count": 0,
    })

    return SafetyDecisionResult(
        task_id=task_id,
        status=next_status,
        safety_status=safety_status,
        report_path=str(report_path),
        artifact_id=artifact_id,
        reasons=reasons,
        state_path=str(state_path),
    )
