"""Senior Review Gate skeleton for SelfDev."""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from selfdev.runtime.artifact_registry import ArtifactRecord, ArtifactRegistry
from selfdev.runtime.kanban import KanbanBoard
from selfdev.runtime.state_manager import StateManager
from selfdev.tools.artifact_gate import validate_artifact_record


VALID_SENIOR_DECISIONS = {
    "approve_for_runner",
    "request_revision",
    "request_specialist_review",
    "block",
    "human_required",
}

DECISION_TO_STATUS = {
    "approve_for_runner": "ready_for_verification",
    "request_revision": "needs_revision",
    "request_specialist_review": "needs_review",
    "block": "blocked",
    "human_required": "human_required",
}


@dataclass
class SeniorReviewResult:
    task_id: str
    decision: str
    status: str
    review_path: str | None = None
    artifact_id: str | None = None
    reasons: list[str] = field(default_factory=list)
    state_path: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "task_id": self.task_id,
            "decision": self.decision,
            "status": self.status,
            "review_path": self.review_path,
            "artifact_id": self.artifact_id,
            "reasons": self.reasons,
            "state_path": self.state_path,
        }


def _now_run_id() -> str:
    return time.strftime("run-%Y%m%d-%H%M%S")


def _write_review_markdown(
    workspace: Path,
    task_id: str,
    decision: str,
    reasons: list[str],
    reviewer_id: str,
) -> Path:
    review_dir = workspace / "reviews"
    review_dir.mkdir(parents=True, exist_ok=True)
    review_path = review_dir / f"{task_id}.senior_review.md"

    reason_text = "\n".join([f"- {reason}" for reason in reasons]) if reasons else "- No blocking reason provided."

    content = f"""# Senior Review

## Task ID

{task_id}

## Reviewer

{reviewer_id}

## Decision

{decision}

## Reasons

{reason_text}

## Notes

This review was generated by the Senior Review Gate skeleton.
"""
    review_path.write_text(content, encoding="utf-8")
    return review_path


def write_senior_review(
    task_id: str,
    decision: str,
    reasons: list[str] | None = None,
    workspace: Path | str = "data/agent_workspace",
    reviewer_id: str = "senior_reviewer",
) -> SeniorReviewResult:
    if decision not in VALID_SENIOR_DECISIONS:
        return SeniorReviewResult(
            task_id=task_id,
            decision=decision,
            status="blocked",
            reasons=[f"Invalid senior decision: {decision}"],
        )

    workspace_path = Path(workspace)
    reasons = reasons or []

    board = KanbanBoard(workspace_path)
    state = StateManager(workspace_path)
    registry = ArtifactRegistry(workspace_path)
    run_id = _now_run_id()

    try:
        task = board.get_task(task_id)
    except KeyError as exc:
        state_path = state.write_state(task_id, {
            "task_id": task_id,
            "run_id": run_id,
            "stage": "senior_review_failed",
            "status": "blocked",
            "reason": [str(exc)],
            "retry_count": 0,
        })
        return SeniorReviewResult(
            task_id=task_id,
            decision=decision,
            status="blocked",
            reasons=[str(exc)],
            state_path=str(state_path),
        )

    if task.get("status") not in {"ready_for_senior", "needs_review"}:
        reason = f"Task status is not ready for senior review: {task.get('status')}"
        state_path = state.write_state(task_id, {
            "task_id": task_id,
            "run_id": run_id,
            "stage": "senior_review_blocked",
            "status": "blocked",
            "reason": [reason],
            "retry_count": 0,
        })
        return SeniorReviewResult(
            task_id=task_id,
            decision=decision,
            status="blocked",
            reasons=[reason],
            state_path=str(state_path),
        )

    review_path = _write_review_markdown(
        workspace=workspace_path,
        task_id=task_id,
        decision=decision,
        reasons=reasons,
        reviewer_id=reviewer_id,
    )

    artifact_id = f"{task_id}.{reviewer_id}.senior_review"
    record = ArtifactRecord(
        artifact_id=artifact_id,
        task_id=task_id,
        agent_id=reviewer_id,
        artifact_type="senior_review",
        path=f"reviews/{task_id}.senior_review.md",
        status="collected",
    )

    gate_result = validate_artifact_record(record.to_dict(), workspace=workspace_path)
    if not gate_result.passed:
        state_path = state.write_state(task_id, {
            "task_id": task_id,
            "run_id": run_id,
            "stage": "senior_review_artifact_invalid",
            "status": "blocked",
            "reason": gate_result.reasons,
            "retry_count": 0,
        })
        return SeniorReviewResult(
            task_id=task_id,
            decision=decision,
            status="blocked",
            review_path=str(review_path),
            artifact_id=artifact_id,
            reasons=gate_result.reasons,
            state_path=str(state_path),
        )

    try:
        registry.register(record)
    except ValueError as exc:
        if "already registered" not in str(exc):
            raise

    board.attach_artifact(task_id, "senior_review", artifact_id)

    next_status = DECISION_TO_STATUS[decision]
    board.update_status(task_id, next_status)

    state_path = state.write_state(task_id, {
        "task_id": task_id,
        "run_id": run_id,
        "stage": "senior_review_completed",
        "status": next_status,
        "current_agent": "senior_reviewer",
        "decision": decision,
        "reason": reasons,
        "last_successful_checkpoint": "senior_review_completed",
        "artifact_id": artifact_id,
        "retry_count": 0,
    })

    return SeniorReviewResult(
        task_id=task_id,
        decision=decision,
        status=next_status,
        review_path=str(review_path),
        artifact_id=artifact_id,
        reasons=reasons,
        state_path=str(state_path),
    )
