"""Verification report flow for SelfDev."""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from selfdev.runtime.artifact_registry import ArtifactRecord, ArtifactRegistry
from selfdev.runtime.kanban import KanbanBoard
from selfdev.runtime.state_manager import StateManager
from selfdev.tools.artifact_gate import validate_artifact_record


@dataclass
class VerificationCheck:
    name: str
    result: str
    blocking: bool
    notes: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "result": self.result,
            "blocking": self.blocking,
            "notes": self.notes,
        }


@dataclass
class VerificationFlowResult:
    task_id: str
    status: str
    verification_status: str
    report_path: str | None = None
    artifact_id: str | None = None
    checks: list[dict[str, Any]] = field(default_factory=list)
    reasons: list[str] = field(default_factory=list)
    state_path: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "task_id": self.task_id,
            "status": self.status,
            "verification_status": self.verification_status,
            "report_path": self.report_path,
            "artifact_id": self.artifact_id,
            "checks": self.checks,
            "reasons": self.reasons,
            "state_path": self.state_path,
        }


def _now_run_id() -> str:
    return time.strftime("run-%Y%m%d-%H%M%S")


def _resolve_required_file(workspace: Path, raw_path: str) -> Path:
    path = Path(raw_path)
    if path.is_absolute():
        return path
    return workspace / path


def _check_required_files(workspace: Path, required_files: list[str]) -> list[VerificationCheck]:
    checks: list[VerificationCheck] = []

    for raw_path in required_files:
        path = _resolve_required_file(workspace, raw_path)
        if path.exists() and path.is_file():
            checks.append(
                VerificationCheck(
                    name=f"required_file:{raw_path}",
                    result="PASS",
                    blocking=True,
                    notes="File exists.",
                )
            )
        else:
            checks.append(
                VerificationCheck(
                    name=f"required_file:{raw_path}",
                    result="FAIL",
                    blocking=True,
                    notes=f"Missing required file: {raw_path}",
                )
            )

    if not required_files:
        checks.append(
            VerificationCheck(
                name="required_files",
                result="PASS",
                blocking=False,
                notes="No required files were provided.",
            )
        )

    return checks


def _write_verification_report(
    workspace: Path,
    task_id: str,
    verification_status: str,
    checks: list[VerificationCheck],
    reasons: list[str],
) -> Path:
    verification_dir = workspace / "verification"
    verification_dir.mkdir(parents=True, exist_ok=True)
    report_path = verification_dir / f"{task_id}.verification_report.md"

    rows = "\n".join(
        [
            f"| {check.name} | {check.result} | {'yes' if check.blocking else 'no'} | {check.notes} |"
            for check in checks
        ]
    )

    reason_text = "\n".join([f"- {reason}" for reason in reasons]) if reasons else "- No blocking reason."

    content = f"""# Verification Report

## Task ID

{task_id}

## Verification Status

{verification_status}

## Checks

| Check | Result | Blocking | Notes |
|---|---|---:|---|
{rows}

## Reasons

{reason_text}

## Notes

This report was generated by the deterministic Verification Report Flow.
"""
    report_path.write_text(content, encoding="utf-8")
    return report_path


def write_verification_report(
    task_id: str,
    required_files: list[str] | None = None,
    workspace: Path | str = "data/agent_workspace",
) -> VerificationFlowResult:
    workspace_path = Path(workspace)
    required_files = required_files or []

    board = KanbanBoard(workspace_path)
    state = StateManager(workspace_path)
    registry = ArtifactRegistry(workspace_path)
    run_id = _now_run_id()

    try:
        task = board.get_task(task_id)
    except KeyError as exc:
        state_path = state.write_state(task_id, {
            "task_id": task_id,
            "run_id": run_id,
            "stage": "verification_failed",
            "status": "blocked",
            "reason": [str(exc)],
            "retry_count": 0,
        })
        return VerificationFlowResult(
            task_id=task_id,
            status="blocked",
            verification_status="BLOCKED",
            reasons=[str(exc)],
            state_path=str(state_path),
        )

    if task.get("status") != "ready_for_verification":
        reason = f"Task status is not ready for Verification Engine: {task.get('status')}"
        state_path = state.write_state(task_id, {
            "task_id": task_id,
            "run_id": run_id,
            "stage": "verification_blocked",
            "status": "blocked",
            "reason": [reason],
            "retry_count": 0,
        })
        return VerificationFlowResult(
            task_id=task_id,
            status="blocked",
            verification_status="BLOCKED",
            reasons=[reason],
            state_path=str(state_path),
        )

    checks = _check_required_files(workspace_path, required_files)
    failed_blocking = [check for check in checks if check.blocking and check.result != "PASS"]

    reasons = [check.notes for check in failed_blocking]
    verification_status = "PASS" if not failed_blocking else "FAIL"
    next_status = "verified" if verification_status == "PASS" else "verification_failed"

    report_path = _write_verification_report(
        workspace=workspace_path,
        task_id=task_id,
        verification_status=verification_status,
        checks=checks,
        reasons=reasons,
    )

    artifact_id = f"{task_id}.verification_engine.verification_report"
    record = ArtifactRecord(
        artifact_id=artifact_id,
        task_id=task_id,
        agent_id="verification_engine",
        artifact_type="verification_report",
        path=f"verification/{task_id}.verification_report.md",
        status="collected",
    )

    gate_result = validate_artifact_record(record.to_dict(), workspace=workspace_path)
    if not gate_result.passed:
        state_path = state.write_state(task_id, {
            "task_id": task_id,
            "run_id": run_id,
            "stage": "verification_artifact_invalid",
            "status": "blocked",
            "reason": gate_result.reasons,
            "retry_count": 0,
        })
        return VerificationFlowResult(
            task_id=task_id,
            status="blocked",
            verification_status="BLOCKED",
            report_path=str(report_path),
            artifact_id=artifact_id,
            reasons=gate_result.reasons,
            state_path=str(state_path),
        )

    try:
        registry.register(record)
    except ValueError as exc:
        if "already registered" not in str(exc):
            raise

    board.attach_artifact(task_id, "verification_report", artifact_id)
    board.update_status(task_id, next_status)

    state_path = state.write_state(task_id, {
        "task_id": task_id,
        "run_id": run_id,
        "stage": "verification_completed",
        "status": next_status,
        "current_agent": "verification_engine",
        "verification_status": verification_status,
        "reason": reasons,
        "last_successful_checkpoint": "verification_completed" if verification_status == "PASS" else None,
        "artifact_id": artifact_id,
        "retry_count": 0,
    })

    return VerificationFlowResult(
        task_id=task_id,
        status=next_status,
        verification_status=verification_status,
        report_path=str(report_path),
        artifact_id=artifact_id,
        checks=[check.to_dict() for check in checks],
        reasons=reasons,
        state_path=str(state_path),
    )
